### ISSUE TITLE
Panic on certain invalid requests

### ISSUE THREAD

**Issue by kayrus** [emersion/go-smtp#129]
Using go-smtp from go-smtp-proxy with the following request:

```
EHLO gmail.com
AUTH LOGIN
***
***
MAIL FROM: foo@bar.com
RCPT TO: foo@bar.com, foo@bar.com
DATA
From: Sender Name <foo@bar.com>
To: foo@bar.com, foo@bar.com
Subject: Test

Test
.
QUIT
```

```
220  ESMTP Service Ready
250-Hello gmail.com
250-PIPELINING
250-8BITMIME
250-ENHANCEDSTATUSCODES
250-CHUNKING
250 AUTH PLAIN LOGIN
334 XXX
334 XXX
235 2.0.0 Authentication succeeded
250 2.0.0 Roger, accepting mail from <foo@bar.com>
501 5.0.0 Invalid RCPT TO address provided
502 5.5.1 Missing RCPT TO command.
501 5.5.2 Bad command
501 5.5.2 Bad command
501 5.5.2 Bad command
500 5.5.2 Speak up
500 5.5.1 Too many errors. Quiting now
```

causes:
```
smtp/server 2020/11/27 14:59:00 panic serving 127.0.0.1:45798: runtime error: invalid memory address or nil pointer dereference
goroutine 65 [running]:
runtime/debug.Stack(0xc00038a8c0, 0xada460, 0xc000076c30)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x9f
github.com/emersion/go-smtp.(*Conn).handle.func1(0xc00038a8c0)
        /app/vendor/github.com/emersion/go-smtp/conn.go:100 +0xfb
panic(0x94d5c0, 0xd4c180)
        /usr/local/go/src/runtime/panic.go:969 +0x1b9
github.com/emersion/go-smtp.(*Conn).handleRcpt(0xc00038a8c0, 0xc0003380c5, 0x24)
        /app/vendor/github.com/emersion/go-smtp/conn.go:494 +0x120
github.com/emersion/go-smtp.(*Conn).handle(0xc00038a8c0, 0xc0003380c0, 0x4, 0xc0003380c5, 0x24)
        /app/vendor/github.com/emersion/go-smtp/conn.go:130 +0x8d6
github.com/emersion/go-smtp.(*Server).handleConn(0xc0002b63c0, 0xc00038a8c0, 0x0, 0x0)
        /app/vendor/github.com/emersion/go-smtp/server.go:154 +0x1ca
created by github.com/emersion/go-smtp.(*Server).Serve
        /app/vendor/github.com/emersion/go-smtp/server.go:126 +0xf8
```

**Comment by kayrus** [comment]
I tried to reproduce this panic trace, but failed. I suppose it was caused by a panic occurred in my `Session` implementation, and it was caught by `recover` call in `handle` method.

Nevertheless I'm against `c.Session().%METHOD%` calls. We need to check whether `c.Session()` returns non `nil`. I'll submit a PR soon to cover this.

**Comment by emersion** [comment]
> Nevertheless I'm against c.Session().%METHOD% calls. We need to check whether c.Session() returns non nil.

It depends. If the session is guaranteed to exist when `Session` is called, or else we've significantly messed up, then it's fine to crash. That results in bug reports, and we can fix our logic error more easily.

**Comment by kayrus** [comment]
What do you suggest? Keep this as is? Contentious issue. I'd implement an error handler, which catch these events in `c.WriteResponse` and print in logs. Ideally refactor the whole error handling logic and cover cases listed in #144.

Meanwhile, to be on the safe side, I'll submit a PR.
